.PHONY: clean

clean:
	-rm -rf build/ dist/ src/*.egg-info pylint.out *.egg
	find . -name \*.pyc -exec rm -f {} \;
	find . -name \*.egg-info -exec rm -rf {} \;
	find ~ -name \*pyPcazip\*.egg -exec rm -rf {} \;
