#!/usr/bin/env python -W ignore
'''
                 *** The command line interface for pyPczcomp ***                                                                                                                                  
'''
import argparse
from pcazip import pypczcomp
from pcazip._version import __version__

########################################################
#                      ENTRY POINT                     #
########################################################
parser = argparse.ArgumentParser()
mandatory = parser.add_argument_group('Mandatory arguments')
mandatory.add_argument('-i','--input', nargs=2, required=True, help='Two pczfiles to compare.')

parser.add_argument('--nvecs', type=int, default=10, help='number of eigenvectors to compare over. Default: 10.')
parser.add_argument('--quick', action='store_true', help='skip time-consuming comparisons')
parser.add_argument('-v','--verbosity', action='count', help="Increase output verbosity.")
parser.add_argument('-V','--version', action='version', version=__version__)

args = parser.parse_args()
pypczcomp.pczcomp(args)
