#!/usr/bin/env python -W ignore
'''
                 *** The command line interface for pyPcaunzip ***                                                                                                                                  
'''
import argparse
from pcazip import pypcaunzip
from pcazip._version import __version__

#######################################################
# ENTRY POINT
#######################################################
parser = argparse.ArgumentParser()
parser.add_argument('-V','--version', action='version', version=__version__)
# Mandatory command line arguments:
mandatory = parser.add_argument_group('Mandatory arguments')
mandatory.add_argument('-t', '--topology',  required=True, help="The topology file. Currently, only PDB files are accepted.")
mandatory.add_argument('-c', '--compressed', required=True, help="The input compressed file.")
mandatory.add_argument('-o', '--output', required=True, help="The output uncompressed trajectory.")


# Optional command line argument:
parser.add_argument('-p', '--preload', action='store_true', help='''Attempt to decompress
entirely in memory. False by default.''')
parser.add_argument('-v', '--verbosity', action='count', help="Increase output verbosity.")

# Now run:
args = parser.parse_args()
pypcaunzip.pcaunzip(args)
